workflows:
  ios-release:
    name: iOS Release (TestFlight)
    instance_type: mac_mini_m2
    max_build_duration: 60

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "ios-v*"
          include: true

    environment:
      node: 20
      xcode: latest
      cocoapods: default

      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: com.apex.aspiral
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App

      # One signing method only (profile + cert references)
      ios_signing:
        provisioning_profiles:
          - aSpiral_iOS_AppStoreConnect_2026
        certificates:
          - aSpiral_dist_2026

    scripts:
      - name: Install dependencies
        script: |
          set -e
          npm ci

      - name: Run tests if present
        script: |
          set -e
          if npm run | grep -qE " test($|:)"; then
            npm test
          else
            echo "ℹ️ No npm test script found — skipping."
          fi

      - name: Run lint if present
        script: |
          set -e
          if npm run | grep -qE " lint($|:)"; then
            npm run lint
          else
            echo "ℹ️ No npm lint script found — skipping."
          fi

      - name: Build web assets
        script: |
          set -e
          npm run build

      - name: Verify web build output exists
        script: |
          set -e
          for d in dist build www; do
            if [ -f "$d/index.html" ]; then
              echo "✅ Found $d/index.html"
              exit 0
            fi
          done
          echo "❌ ERROR: No index.html found in dist/, build/, or www/."
          echo "Fix frontend build output OR capacitor.config webDir."
          exit 1

      - name: Sync Capacitor (iOS)
        script: |
          set -e
          npx cap sync ios

      - name: Verify iOS web assets copied
        script: |
          set -e
          if [ -f "ios/App/App/public/index.html" ]; then
            echo "✅ ios/App/App/public/index.html exists"
          else
            echo "❌ ERROR: ios/App/App/public/index.html missing after cap sync."
            echo "This causes the blank/purple screen."
            exit 1
          fi

      - name: Set iOS version from tag (ios-vX.Y.Z) + build number
        script: |
          set -e
          VERSION="${CM_TAG#ios-v}"
          BUILD="${CM_BUILD_NUMBER:-1}"
          PLIST="ios/App/App/Info.plist"

          echo "Setting iOS version: $VERSION ($BUILD)"

          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" >/dev/null 2>&1 \
            && /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $VERSION" "$PLIST"

          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" >/dev/null 2>&1 \
            && /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD" "$PLIST"

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install

      - name: Compliance Check
        script: |
          set -e
          RESULT=$(/usr/libexec/PlistBuddy -c "Print :ITSAppUsesNonExemptEncryption" ios/App/App/Info.plist 2>/dev/null || echo "MISSING")
          if [ "$RESULT" != "false" ] && [ "$RESULT" != "MISSING" ]; then
            echo "WARNING: ITSAppUsesNonExemptEncryption is $RESULT (Should be false)"
          else
            echo "✅ ITSAppUsesNonExemptEncryption OK ($RESULT)"
          fi

      - name: Set up code signing
        script: |
          set -e
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          set -e
          mkdir -p build/ios/ipa
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --ipa-path build/ios/ipa/aSpiral.ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - ios/App/App/public/index.html

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

      email:
        recipients:
          - michael@apexbiz.io
        notify:
          success: true
          failure: true
