workflows:
  aspiral_ios_testflight:
    name: aSpiral iOS -> TestFlight (Green Next Run)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      xcode: 16.4
      node: 22
      cocoapods: default

      groups:
        - ios_credentials
        - appstore_credentials

      vars:
        NODE_OPTIONS: "--max_old_space_size=8192"

        XCODE_SCHEME: "App"

        IOS_PROJECT_PATH: "ios/App/App.xcodeproj"
        IOS_WORKSPACE_PATH: "ios/App/App.xcworkspace"
        IOS_FALLBACK_WORKSPACE_PATH: "ios/App/App.xcodeproj/project.xcworkspace"

        INFO_PLIST_PATH: "ios/App/App/Info.plist"
        IPA_PATH: "build/ios/ipa/App.ipa"

    scripts:
      - name: Preflight (fail fast + normalize Key ID)
        script: |
          set -euo pipefail

          # Normalize Key ID drift: prefer APP_STORE_CONNECT_KEY_ID, fallback to mis-cased KEY_iD
          if [ -z "${APP_STORE_CONNECT_KEY_ID:-}" ] && [ -n "${APP_STORE_CONNECT_KEY_iD:-}" ]; then
            echo "APP_STORE_CONNECT_KEY_ID=${APP_STORE_CONNECT_KEY_iD}" >> "$CM_ENV"
            export APP_STORE_CONNECT_KEY_ID="${APP_STORE_CONNECT_KEY_iD}"
          fi

          required_vars=(
            TEAM_ID
            BUNDLE_ID
            APP_STORE_CONNECT_ISSUER_ID
            APP_STORE_CONNECT_PRIVATE_KEY
            APP_STORE_CONNECT_KEY_ID
            CERTIFICATE_PRIVATE_KEY
          )

          for v in "${required_vars[@]}"; do
            if [ -z "${!v:-}" ]; then
              echo "Missing required env var: ${v}"
              exit 1
            fi
          done

          test -f package.json || (echo "package.json missing at repo root" && exit 1)
          test -f "$INFO_PLIST_PATH" || (echo "Info.plist missing at $INFO_PLIST_PATH" && exit 1)

          echo "Preflight OK"

      - name: Initialize keychain + fetch/create signing files (fail fast on Apple auth)
        script: |
          set -euo pipefail

          keychain initialize

          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY \
            "$BUNDLE_ID"

          keychain add-certificates
          echo "Signing assets ready"

      - name: Pin npm (matches known-good lane behavior)
        script: |
          set -euo pipefail
          node -v
          npm install -g npm@10
          npm -v

      - name: Install JS deps
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm ci

      - name: Build web assets (OOM hardened)
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm run build

      - name: Capacitor sync iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: CocoaPods (ONLY if Podfile exists anywhere under ios/)
        script: |
          set -euo pipefail

          PODFILE_PATH="$(find ios -maxdepth 4 -name Podfile -print -quit || true)"
          if [ -n "${PODFILE_PATH}" ]; then
            POD_DIR="$(dirname "${PODFILE_PATH}")"
            echo "Podfile found at: ${PODFILE_PATH}"
            cd "${POD_DIR}"
            pod install
            cd "$CM_BUILD_DIR"
          else
            echo "No Podfile found. Skipping CocoaPods (SPM-based project)."
          fi

      - name: Resolve iOS build target (workspace vs project) AFTER sync/pods
        script: |
          set -euo pipefail

          if [ -d "$IOS_WORKSPACE_PATH" ]; then
            echo "BUILD_TARGET=workspace" >> "$CM_ENV"
            echo "XCODE_WORKSPACE=$IOS_WORKSPACE_PATH" >> "$CM_ENV"
            echo "Using workspace: $IOS_WORKSPACE_PATH"
          elif [ -d "$IOS_FALLBACK_WORKSPACE_PATH" ]; then
            echo "BUILD_TARGET=workspace" >> "$CM_ENV"
            echo "XCODE_WORKSPACE=$IOS_FALLBACK_WORKSPACE_PATH" >> "$CM_ENV"
            echo "Using fallback workspace: $IOS_FALLBACK_WORKSPACE_PATH"
          elif [ -d "$IOS_PROJECT_PATH" ]; then
            echo "BUILD_TARGET=project" >> "$CM_ENV"
            echo "XCODE_PROJECT=$IOS_PROJECT_PATH" >> "$CM_ENV"
            echo "Using project: $IOS_PROJECT_PATH"
          else
            echo "No workspace or project found. Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi

      - name: Set unique build number (TestFlight-safe)
        script: |
          set -euo pipefail

          BUILD="$(date -u +%Y%m%d%H%M%S)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$INFO_PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD" "$INFO_PLIST_PATH"

          echo "CFBundleVersion set to $BUILD"

      - name: Configure code signing (Internal Testing Only)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Build IPA
        script: |
          set -euo pipefail
          mkdir -p build/ios/ipa

          if [ "${BUILD_TARGET:-}" = "workspace" ]; then
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --config Release \
              --ipa-path "$IPA_PATH"
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --config Release \
              --ipa-path "$IPA_PATH"
          fi

      - name: Verify IPA exists
        script: |
          set -euo pipefail
          test -f "$IPA_PATH" || (echo "IPA not found at $IPA_PATH" && exit 1)
          echo "IPA OK: $IPA_PATH"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
