workflows:
  aspiral_ios_testflight:
    name: aSpiral iOS -> TestFlight (Green Next Run)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      xcode: 16.4
      node: 22
      cocoapods: default
      groups:
        - ios_credentials
        - appstore_credentials
      vars:
        NODE_OPTIONS: "--max_old_space_size=8192"

        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_FALLBACK_WORKSPACE: "ios/App/App.xcodeproj/project.xcworkspace"
        INFO_PLIST_PATH: "ios/App/App/Info.plist"

        IPA_PATH: "build/ios/ipa/App.ipa"

    scripts:
      - name: Preflight (fail fast, normalize Key ID)
        script: |
          set -euo pipefail

          # Accept any one of these, but standardize on KEY_IDENTIFIER
          KEY="${APP_STORE_CONNECT_KEY_IDENTIFIER:-${APP_STORE_CONNECT_KEY_ID:-${APP_STORE_CONNECT_KEY_iD:-}}}"
          if [ -z "${KEY}" ]; then
            echo "Missing App Store Connect Key ID env var (set APP_STORE_CONNECT_KEY_IDENTIFIER)."
            exit 1
          fi
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=$KEY" >> "$CM_ENV"

          required_vars=(
            TEAM_ID
            BUNDLE_ID
            APP_STORE_CONNECT_ISSUER_ID
            APP_STORE_CONNECT_PRIVATE_KEY
            CERTIFICATE_PRIVATE_KEY
          )

          for v in "${required_vars[@]}"; do
            if [ -z "${!v:-}" ]; then
              echo "Missing required env var: ${v}"
              exit 1
            fi
          done

          if [ ! -f "package.json" ]; then
            echo "package.json missing at repo root"
            exit 1
          fi

          if [ ! -f "$INFO_PLIST_PATH" ]; then
            echo "Info.plist missing at $INFO_PLIST_PATH"
            exit 1
          fi

          echo "Preflight OK"

      - name: Pin npm (matches known-good lane behavior)
        script: |
          set -euo pipefail
          node -v
          npm install -g npm@10
          npm -v

      - name: Install JS deps
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm ci

      - name: Build web assets (OOM hardened)
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm run build

      - name: Capacitor sync iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: CocoaPods install
        script: |
          set -euo pipefail
          cd ios/App
          pod install
          cd ../..

      - name: Resolve workspace (prefer App.xcworkspace after pods)
        script: |
          set -euo pipefail

          if [ -d "$XCODE_WORKSPACE" ]; then
            echo "Using workspace: $XCODE_WORKSPACE"
          elif [ -d "$XCODE_FALLBACK_WORKSPACE" ]; then
            echo "XCODE_WORKSPACE=$XCODE_FALLBACK_WORKSPACE" >> "$CM_ENV"
            echo "Using fallback workspace: $XCODE_FALLBACK_WORKSPACE"
          else
            echo "No workspace found. Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi

      - name: Set unique build number (TestFlight-safe)
        script: |
          set -euo pipefail
          BUILD="$(date -u +%Y%m%d%H%M%S)"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$INFO_PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD" "$INFO_PLIST_PATH"

          echo "CFBundleVersion set to $BUILD"

      - name: Initialize keychain + fetch/create signing files (explicit flags)
        script: |
          set -euo pipefail

          keychain initialize

          # Codemagic CLI tools documented pattern
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY \
            "$BUNDLE_ID"

          keychain add-certificates

      - name: Configure code signing (Internal Testing Only)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Build IPA
        script: |
          set -euo pipefail
          mkdir -p build/ios/ipa

          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --ipa-path "$IPA_PATH"

      - name: Verify IPA exists
        script: |
          set -euo pipefail
          test -f "$IPA_PATH" || (echo "IPA not found at $IPA_PATH" && exit 1)
          echo "IPA OK: $IPA_PATH"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
