import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { Resend } from "https://esm.sh/resend@2.0.0";
import { corsHeaders } from "../_shared/cors.ts";

interface InvitePayload {
  email: string;
  role: 'admin' | 'member' | 'viewer';
  organization_id: string;
  name?: string;
}

serve(async (req) => {
  // Handle CORS preflight request
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const resendApiKey = Deno.env.get('RESEND_API_KEY');

    if (!resendApiKey) {
      throw new Error('RESEND_API_KEY is not set');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const resend = new Resend(resendApiKey);

    // Get the user from the authorization header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Missing Authorization header');
    }

    const { data: { user }, error: userError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    );

    if (userError || !user) {
      throw new Error('Invalid user token');
    }

    // Parse request body
    const { email, role, organization_id, name } = await req.json() as InvitePayload;

    if (!email || !role || !organization_id) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: email, role, organization_id' }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Verify the inviter is a member of the organization
    const { data: membership, error: membershipError } = await supabase
      .from('organization_members')
      .select('role')
      .eq('org_id', organization_id)
      .eq('user_id', user.id)
      .single();

    if (membershipError || !membership) {
      return new Response(
        JSON.stringify({ error: 'You are not a member of this organization' }),
        {
          status: 403,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Check if the inviter has permission to invite (admins and owners usually)
    // For now, let's assume any member can invite, or check specific roles if needed.
    // The requirement didn't specify strict role checks for *inviting*, but usually admins/owners.
    // Let's allow 'admin' and 'owner' roles to invite.
    if (membership.role !== 'admin' && membership.role !== 'owner') {
       return new Response(
        JSON.stringify({ error: 'Only admins and owners can invite new members' }),
        {
          status: 403,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Create the invitation record
    const { data: invitation, error: inviteError } = await supabase
      .from('team_invitations')
      .insert({
        email,
        role,
        organization_id,
        invited_by: user.id,
        status: 'pending',
        // Token is generated by default in DB if not provided, but we need it for the email.
        // The table definition says: token TEXT UNIQUE DEFAULT gen_random_uuid()::text
        // So we can let DB generate it and return it.
      })
      .select('token')
      .single();

    if (inviteError) {
      // Check for duplicate invitation
      if (inviteError.code === '23505') { // Unique violation
         return new Response(
          JSON.stringify({ error: 'An invitation for this email already exists' }),
          {
            status: 409,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          }
        );
      }
      throw inviteError;
    }

    const inviteLink = `${req.headers.get('origin') || 'https://www.tradeline247ai.com'}/auth/accept-invite?token=${invitation.token}`;

    // Send email via Resend
    const { error: emailError } = await resend.emails.send({
      from: 'TradeLine 24/7 <invites@tradeline247ai.com>', // Or a configured sender
      to: [email],
      subject: 'You have been invited to join TradeLine 24/7',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>You've been invited!</h2>
          <p>Hello${name ? ' ' + name : ''},</p>
          <p>You have been invited to join the <strong>TradeLine 24/7</strong> workspace.</p>
          <p>Role: <strong>${role}</strong></p>
          <div style="margin: 30px 0;">
            <a href="${inviteLink}" style="background-color: #000; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">Accept Invitation</a>
          </div>
          <p>Or copy and paste this link into your browser:</p>
          <p><a href="${inviteLink}">${inviteLink}</a></p>
          <p>This invitation will expire in 7 days.</p>
        </div>
      `,
    });

    if (emailError) {
      // If email fails, we might want to delete the invitation or just report error.
      // For now, let's report it but keep the invitation (can be resent later).
      console.error('Failed to send email:', emailError);
       return new Response(
        JSON.stringify({ warning: 'Invitation created but email failed to send', error: emailError }),
        {
          status: 200, // Partial success
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    return new Response(
      JSON.stringify({ message: 'Invitation sent successfully' }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error processing invitation:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
