// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY: Environment variables required - no hardcoded fallbacks
// Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your environment
const url = import.meta.env.VITE_SUPABASE_URL;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Safely detect browser storage to avoid SSR/build ReferenceErrors
const safeStorage: Storage | undefined =
  typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
    ? window.localStorage
    : undefined;

let supabase: SupabaseClient<Database> | null = null;

if (url && anonKey) {
  supabase = createClient<Database>(url, anonKey, {
    auth: {
      // Only persist session when running in the browser
      storage: safeStorage,
      persistSession: typeof window !== 'undefined',
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
} else {
  if (typeof window !== 'undefined') {
    console.error(
      '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY! Check your .env or Vercel settings.'
    );
  } else {
    console.info(
      '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY; Supabase client disabled for this build.'
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };
export const isSupabaseEnabled = supabase !== null;